"""added test notes

Revision ID: ccb551303ed6
Revises: 637b63411688
Create Date: 2023-01-01 17:35:41.124810

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ccb551303ed6"
down_revision = "637b63411688"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notes")
    # ### end Alembic commands ###
